package lafdilibilal.entities;

public enum Genere {
    FANTASY, FANTASCIENZA, GIALLO, THRILLER, HORROR, ROMANZO, STORICO, BIOGRAFIA, AVVENTURA, POESIA,
    DRAMMATICO, COMMEDIA, SAGGISTICA, INFORMATICA, SCIENTIFICO, SPORT, FUMETTO
}
